language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
licenses:
  - android-sdk-preview-license-c81a61d9
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - linters/install-linters.sh
  - ci/install-protoc.sh
script:
  - ci/create-gradle-wrapper-4.6.sh
  - sh gradlew reactive-blerpc:assemble reactive-blerpc:test
  - ci/generate-reactive-plugin.sh
  - sh gradlew assemble testReleaseUnitTest
  - reactive-blerpc-test/tests/end-to-end-tests.sh
  - linters/run-linters.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then
          sh gradlew blerpc:bintrayUpload -PbintrayUser=monnoroch -PbintrayKey="$BINTRAY_API_KEY" -PdryRun=false;
          sh gradlew blerpcproto:bintrayUpload -PbintrayUser=monnoroch -PbintrayKey="$BINTRAY_API_KEY" -PdryRun=false;
          sh gradlew reactive-blerpc:bintrayUpload -PbintrayUser=monnoroch -PbintrayKey="$BINTRAY_API_KEY" -PdryRun=false;
    fi
notifications:
  email: false
